version: '3.4'

services:
  redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: ${APP_NAME}-redis-cluster
    ports:
      - '7000-7005'
    networks:
      - default

  mysql:
    container_name: ${APP_NAME}--mysql
    image: mysql:5.7.27
    restart: always
    volumes:
      - "mysql:/var/lib/mysql"
      - ./:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: library
      MYSQL_PASSWORD: 12345678
      MYSQL_USER: library
    networks:
      - default
    ports:
      - ${MYSQL_PORT_EXPOSE}:3306

  php:
    container_name: ${APP_NAME}-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: build
      args:
        - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
      - .:/app
    depends_on:
      - redis-cluster
      - mysql
    env_file: .env
    networks:
      - default

  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: docker/nginx
    depends_on:
      - php
    volumes:
      - .:/app
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
    networks:
      default:
        aliases:
          - library.com
networks:
  default:
    external:
      name: library_nw

volumes:
  mysql:
    driver: local