version: '3.4'

volumes:
  mongodb:
    driver: local

services:
  redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: ${APP_NAME}-redis-cluster
    ports:
      - '7000-7005'
    networks:
      - default

  php:
    container_name: ${APP_NAME}-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: build
    volumes:
      - .:/app
    depends_on:
      - redis-cluster
    env_file: .env
    networks:
      - default

  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: docker/nginx
    depends_on:
      - php
    volumes:
      - .:/app
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
    networks:
      default:
        aliases:
          - library.com
networks:
  default:
    external:
      name: library_nw
