Kennynguyeenx\LibraryHexagonal\Domain\Borrowing\Core\Model\AvailableBook:
  type: entity
  repositoryClass: Kennynguyeenx\LibraryHexagonal\Infrastructure\Domain\Borrowing\Core\Model\AvailableBook\DoctrineAvailableBookRepository
  table: available
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    bookId:
      type: integer
      column: book_id
  uniqueConstraints:
    book_id_UNIQUE:
      columns: book_id