Kennynguyeenx\LibraryHexagonal\Domain\Borrowing\Core\Model\BorrowedBook:
  type: entity
  repositoryClass: Kennynguyeenx\LibraryHexagonal\Infrastructure\Domain\Borrowing\Core\Model\BorrowedBook\DoctrineBorrowedBookRepository
  table: borrowed
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    bookId:
      type: integer
      column: book_id
    userId:
      type: integer
      column: user_id
    borrowedDate:
      type: datetime
      column: borrowed_date
  uniqueConstraints:
    book_id_UNIQUE:
      columns: book_id