Kennynguyeenx\LibraryHexagonal\Domain\User\Core\Model\User:
  type: entity
  repositoryClass: Kennynguyeenx\LibraryHexagonal\Infrastructure\Domain\User\Core\Model\User\DoctrineUserRepository
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstName:
      type: string
      length: 255
      column: first_name
    lastName:
      type: string
      length: 255
      column: last_name
    email:
      type: string
      length: 45
  uniqueConstraints:
    email_UNIQUE:
      columns: email